/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * 개설과목입력사항.java
 *
 * Created on 2010. 6. 25, 오후 3:40:15
 */

package javaapplication1;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.*;
import javax.swing.table.*;
import java.awt.event.*;
import java.util.*;
/**
 *
 * @author Jin
 */
public class 개설과목입력사항 extends javax.swing.JFrame   {
    static public Object []row = new Object[10];
    static public String 입력;
    static public 학과장메뉴 학과장;
    /** Creates new form 개설과목입력사항 */
    public 개설과목입력사항() {
        initComponents();
    }
    public 개설과목입력사항(학과장메뉴 학과장, String 입력) {
        initComponents();
        this.학과장 = 학과장;
        this.입력 = 입력;
    }
    public 개설과목입력사항(학과장메뉴 학과장, Object []row, String 입력) {
        initComponents();
        this.학과장 = 학과장;

        for(int i=0; i<10; i++)
            this.row[i] = row[i];

        교과목코드입력.setText((String)row[3]);
        교과목명입력.setText((String)row[2]);
        이수구분입력.setText((String)row[1]);
        담당교수입력.setText((String)row[5]);
        학년입력.setText((String)row[0]);
        학점입력.setText((String)row[4]);
        강의시간입력.setText(row[7].toString());
        제한인원입력.setText((String)row[8]);

        this.입력 = 입력;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        학년입력 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        담당교수입력 = new javax.swing.JTextField();
        강의시간입력 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        이수구분입력 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        제한인원입력 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        학점입력 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        교과목코드입력 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        교과목명입력 = new javax.swing.JTextField();
        입력버튼 = new javax.swing.JButton();
        취소버튼 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel10.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        jLabel10.setText("학           년 :");

        학년입력.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        jLabel13.setText("담 당 교 수 :");

        담당교수입력.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N

        강의시간입력.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        jLabel11.setText("이 수 구 분 :");

        이수구분입력.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N

        jLabel16.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        jLabel16.setText("제 한 인 원 :");

        제한인원입력.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N

        jLabel18.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        jLabel18.setText("학           점 :");

        학점입력.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N

        jLabel15.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        jLabel15.setText("강 의 시 간 :");

        교과목코드입력.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        교과목코드입력.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel12.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        jLabel12.setText("교과목코드 :");

        jLabel17.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        jLabel17.setText("교 과 목 명 :");

        교과목명입력.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel17)
                    .addComponent(jLabel13)
                    .addComponent(jLabel10)
                    .addComponent(jLabel18)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(이수구분입력, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(담당교수입력, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(학년입력, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(학점입력, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(강의시간입력, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(제한인원입력, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(교과목명입력, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(교과목코드입력, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel12)
                    .addContainerGap(231, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(교과목코드입력, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(교과목명입력, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(이수구분입력, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(담당교수입력, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(학년입력, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(학점입력, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(강의시간입력, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(제한인원입력, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel12)
                    .addContainerGap(261, Short.MAX_VALUE)))
        );

        입력버튼.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        입력버튼.setText("입력");
        입력버튼.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                입력버튼ActionPerformed(evt);
            }
        });

        취소버튼.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        취소버튼.setText("취소");
        취소버튼.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                취소버튼ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(입력버튼)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(취소버튼)
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(입력버튼)
                    .addComponent(취소버튼))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void 입력버튼ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_입력버튼ActionPerformed
        // TODO add your handling code here:
        // 입력버튼
        row[0] = 학년입력.getText();
        row[1] = 이수구분입력.getText();
        row[2] = 교과목명입력.getText();
        row[3] = 교과목코드입력.getText();
        row[4] = 학점입력.getText();
        row[5] = 담당교수입력.getText();
        row[7] = 강의시간입력.getText();
        row[8] = 제한인원입력.getText();

        if(입력.equals("수정"))
        {
            학과장.수정결과(row);
        }
        else if(입력.equals("등록"))
        {
            학과장.등록결과(row);
        }

        this.dispose();
    }//GEN-LAST:event_입력버튼ActionPerformed

    private void 취소버튼ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_취소버튼ActionPerformed
        // TODO add your handling code here:
        // 취소버튼
        학과장.프레임출력();
        this.dispose();
    }//GEN-LAST:event_취소버튼ActionPerformed
    public void 바보() {

    }
    /**
    * @param args the command line arguments
    */
    public static Object main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new 개설과목입력사항().setVisible(true);
            }
        });
        return row;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField 강의시간입력;
    private javax.swing.JTextField 교과목명입력;
    private javax.swing.JTextField 교과목코드입력;
    private javax.swing.JTextField 담당교수입력;
    private javax.swing.JTextField 이수구분입력;
    private javax.swing.JButton 입력버튼;
    private javax.swing.JTextField 제한인원입력;
    private javax.swing.JButton 취소버튼;
    private javax.swing.JTextField 학년입력;
    private javax.swing.JTextField 학점입력;
    // End of variables declaration//GEN-END:variables

}
